### ISSUE TITLE
Not available for Windows Phone 10

### ISSUE THREAD

**Issue by sandervandevelde** [CamSoper/WhosDown#4]
The windows Store does not let us download it on Windows Phone 10. Should be awesome to use it within Continuum.

**Comment by CamSoper** [comment]
I agree that it would be useful for Continuum, and I accidentally left if on for WP10 download when I first published it.  My question is, how would you scan the QR code?

**Comment by CamSoper** [comment]
Included in 1.1.5.0 (currently in certification in the store - Should be published tomorrow)
