### ISSUE TITLE
Figure out a Continuum strategy

### ISSUE THREAD

**Issue by CamSoper** [CamSoper/WhosDown#7]
The app was originally available for Windows 10 Mobile as well, but I turned it off because there's no way to scan the QR code on a mobile device.  However, several people have asked if I could re-enable this for purposes of Continuum on Lumia 950/XL devices.  That I can do in the Store easily enough, but I need a way to tell mobile users that the app is intended for Continuum, not a mobile screen.

**Comment by sebagomez** [comment]
I believe it'll be confusing for non technical users and the app will end up with bad reviews because of that. People do not read the instructions
Just my thoughts

**Comment by sebagomez** [comment]
Also, I just came across to [this post](http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_continuum/list-of-apps-that-support-continuum/b48311fa-2f37-4565-868f-981628fbacbc?auth=1) which states that WhatsApp is working on Continuum

**Comment by CamSoper** [comment]
Included in new release.
